homepage:
    path: //
    defaults: { _controller: FuroBundle:Furo:index }

furo_list:
    path: /furo/list
    defaults: { _controller: FuroBundle:Furo:list }

furo_new:
    path: /furo/new/{step}
    defaults: { _controller: FuroBundle:Furo:new }
    requirements:
        step: '\d+'

furo_view:
    path: /furo/view/{id}
    defaults: { _controller: FuroBundle:Furo:view }
    requirements:
        id: '\d+'

login:
    path: /login
    defaults: { _controller: FuroBundle:Access:login }